### ISSUE TITLE
Returns [ svg ]

### ISSUE THREAD

**Issue by balexbyrd** [Objectway/d3-server-renderer#1]
In my HTML page, it's only returning '[ svg ]' and not actually painting the visual. I tried this with both the radial tree and the pie chart. I think it may have something to do with how it returns the svgObject in the d3 js file.

return new xmldom.XMLSerializer().serializeToString(svgObject[0][0]);

Any help? Thanks in advance.

**Comment by micheledisalvatore** [comment]
Hi @balexbyrd thank you! I've noticed that the problem is in the xmldom dependency. Now it's fixed!
