### ISSUE TITLE
[svg] displayed on windows

### ISSUE THREAD

**Issue by brusand** [Objectway/d3-server-renderer#3]
Hi,

i clone your project on windows 7 and when i launch the browser on localhost:1337, the result is [svg] and no svg chart displayed.

Any idea ?

Best regards
Bruno

**Comment by micheledisalvatore** [comment]
Check the dependencies version 
`$ npm ls`

and be sure that xmldom has the version 0.1.19. The problem is in the versions (>0.1.19)

**Comment by brusand** [comment]
thks,  it s works like a charm :)

2016-05-17 12:58 GMT+02:00 Michele Di Salvatore notifications@github.com:
